bootstrapped react, testing, linting, created app component
Recidiviz/justice-counts-components pull request #15
Opened 2020-11-30 12:23 UTC by Wmaileq

## Description of the change

- bootstrapped app skeleton, linting and testing utils
- added fonts and created UI for the main page
- added initial test

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1 , Closes #2 , Closes #3 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-11-30 20:32 UTC, jessex requested changes
Off to a great start, @Wmaileq! Just two minor formatting notes for you.

2020-12-01 12:25 UTC, Wmaileq commented
@jessex Percent in the card made with 500 weight font, so need corresponding font file (supervision success had only 400 and 700)

2020-12-01 19:00 UTC, jessex reviewed
Looking good so far, @Wmaileq! Are you planning to do more in this initial PR (e.g. add skeletons for the graphs, or add the rest of the arrows to the flowchart) or is this done for now?

Regarding the fonts, which font file do you need exactly? Now that you have comment abilities on the PRD, would you mind asking Humphrey there directly?

2020-12-02 08:42 UTC, Wmaileq commented
@jessex I am thinking about adding all the UI in this PR.

2020-12-02 20:00 UTC, jessex requested changes
Thanks, @Wmaileq! A few comments for your latest batch here.

Also, I see the following errors in the console logs that we'll want to take care of before merging:

<img width="1110" alt="Screen Shot 2020-12-02 at 12 53 58" src="https://user-images.githubusercontent.com/431895/100924806-54603380-349e-11eb-8254-1050d9ea57b1.png">

2020-12-03 08:19 UTC, Wmaileq commented on src/FlowDiagram/FlowDiagram.js
> +          <Arrow />
Now arrows color goes from cards. `Card__arrow` class. It makes all arrows gray when the card itself disabled. 
But seems like it is not a working solution, I will introduce a new prop in the arrow itself.

2020-12-03 23:29 UTC, jessex approved these changes
Looks great, @Wmaileq! Well done. Are you planning to continue more work on this branch or am I clear to merge this one?

2020-12-04 14:38 UTC, Wmaileq commented
@jessex feel free to merge this.

2020-12-04 18:03 UTC, merged